# Docker configuration for building/testting Giri against LLVM 8.0.0
# Used by agents to determine the correct container setup.

base_image: "ubuntu:18.04"
reason: "Ubuntu 18.04 is the release LLVM 8.0.0 prebuilt binaries target"

llvm_install:
  version: "8.0.0"
  method: "prebuilt_tarball"
  tarball: "clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz"
  url: "https://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz"
  install_path: "/usr/local/llvm"
  script: "utils/install_llvm.sh 8.0.0"

cmake:
  min_version: "3.10"
  note: "Ubuntu 18.04 ships CMake 3.10; do not use -S/-B flags (require 3.13+)"

env_vars:
  LLVM_HOME: "/usr/local/llvm"
  LLVM_DIR: "/usr/local/llvm/lib/cmake/llvm"
  PATH: "/usr/local/llvm/bin:$PATH"
  TEST_PARALLELISM: "seq"

docker_image_name: "giri-llvm8"
build_command: "docker build -t giri-llvm8 ."
iterate_command: "docker run -it --rm giri-llvm8 bash"

packages:
  - wget
  - xz-utils
  - ca-certificates
  - cmake
  - make
  - g++