# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /giri

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /giri

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /giri/CMakeFiles /giri/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /giri/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dgutility

# Build rule for target.
dgutility: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dgutility
.PHONY : dgutility

# fast build rule for target.
dgutility/fast:
	$(MAKE) -f lib/Utility/CMakeFiles/dgutility.dir/build.make lib/Utility/CMakeFiles/dgutility.dir/build
.PHONY : dgutility/fast

#=============================================================================
# Target rules for targets named giri

# Build rule for target.
giri: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 giri
.PHONY : giri

# fast build rule for target.
giri/fast:
	$(MAKE) -f lib/Giri/CMakeFiles/giri.dir/build.make lib/Giri/CMakeFiles/giri.dir/build
.PHONY : giri/fast

#=============================================================================
# Target rules for targets named rtgiri

# Build rule for target.
rtgiri: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtgiri
.PHONY : rtgiri

# fast build rule for target.
rtgiri/fast:
	$(MAKE) -f runtime/Giri/CMakeFiles/rtgiri.dir/build.make runtime/Giri/CMakeFiles/rtgiri.dir/build
.PHONY : rtgiri/fast

#=============================================================================
# Target rules for targets named tracer

# Build rule for target.
tracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tracer
.PHONY : tracer

# fast build rule for target.
tracer/fast:
	$(MAKE) -f tools/Tracer/CMakeFiles/tracer.dir/build.make tools/Tracer/CMakeFiles/tracer.dir/build
.PHONY : tracer/fast

#=============================================================================
# Target rules for targets named prtrace

# Build rule for target.
prtrace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prtrace
.PHONY : prtrace

# fast build rule for target.
prtrace/fast:
	$(MAKE) -f tools/PrintTrace/CMakeFiles/prtrace.dir/build.make tools/PrintTrace/CMakeFiles/prtrace.dir/build
.PHONY : prtrace/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... dgutility"
	@echo "... giri"
	@echo "... rtgiri"
	@echo "... tracer"
	@echo "... prtrace"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

