##===- giri/test/UnitTests/test11/Makefile -----------------*- Makefile -*-===##

NAME = hello2p
LDFLAGS = -pthread
INPUT ?= 4
# total_len = 14 + 14 + 14 + 12 = 54
EXPECTED_EXIT = 54

include ../../Makefile.common