##===- giri/test/UnitTests/test14/Makefile -----------------*- Makefile -*-===##

NAME = struct-ptr
LDFLAGS = -lm
INPUT ?= 10
# printf("%d\n", 5) prints 2 chars
EXPECTED_EXIT = 2

include ../../Makefile.common