##===- giri/test/UnitTests/test12/Makefile -----------------*- Makefile -*-===##

NAME = psum
LDFLAGS = -pthread
INPUT ?= 16 8
# result = sum(0..255) = 32640; 32640 % 31 = 5
EXPECTED_EXIT = 5

include ../../Makefile.common