##===- giri/test/UnitTests/test13/Makefile -----------------*- Makefile -*-===##

NAME = struct
LDFLAGS = -lm
INPUT ?= 10
# printf("%d\n", 5) prints 2 chars
EXPECTED_EXIT = 2

include ../../Makefile.common